//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STGchannelMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Test_jvspkkEntities : DbContext
    {
        public Test_jvspkkEntities()
            : base("name=Test_jvspkkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<q_import_bh> q_import_bh { get; set; }
        public virtual DbSet<q_import_bp> q_import_bp { get; set; }
    
        public virtual ObjectResult<Nullable<long>> q_get_next_tranid(Nullable<short> foretagkod, ObjectParameter tranid, string calltype)
        {
            var foretagkodParameter = foretagkod.HasValue ?
                new ObjectParameter("foretagkod", foretagkod) :
                new ObjectParameter("foretagkod", typeof(short));
    
            var calltypeParameter = calltype != null ?
                new ObjectParameter("calltype", calltype) :
                new ObjectParameter("calltype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("q_get_next_tranid", foretagkodParameter, tranid, calltypeParameter);
        }
    }
}
