//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STGchannelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_Customer_items_2_Jeeves
    {
        public short foretagkod { get; set; }
        public string lagstalle { get; set; }
        public string q_profit_center { get; set; }
        public string q_material_group { get; set; }
        public string q_isbn_no { get; set; }
        public string artnr { get; set; }
        public string artbeskr { get; set; }
        public string q_itemtypecd1 { get; set; }
        public string q_artkat { get; set; }
        public string artlistpris { get; set; }
        public string momskod { get; set; }
        public string itemstatuscode { get; set; }
        public string q_sap_item_no { get; set; }
        public string artstatnr { get; set; }
        public string UpdateStatusDescr { get; set; }
        public string itemtypecd2 { get; set; }
        public string q_wsoy_libraryclass { get; set; }
        public string varugruppkod { get; set; }
        public Nullable<System.DateTime> q_fetched_by_inobiz { get; set; }
        public string ar_q_edition_counter { get; set; }
        public string artkalkber { get; set; }
        public string artkalkpris { get; set; }
        public string q_publisher_itemid { get; set; }
        public string artvikt { get; set; }
        public string q_publ_date { get; set; }
        public string q_artbeskr_kiva { get; set; }
        public string q_planned_arrival_date { get; set; }
        public string q_pl_garr_date { get; set; }
        public string ArtBeskrSpec { get; set; }
        public string q_author { get; set; }
        public string q_edt { get; set; }
        public string q_aof { get; set; }
        public string q_au { get; set; }
        public string q_des { get; set; }
        public string q_eic { get; set; }
        public string q_ill { get; set; }
        public string q_ot { get; set; }
        public string q_pho { get; set; }
        public string q_pre { get; set; }
        public string q_rea { get; set; }
        public string q_tra { get; set; }
        public string itemtypecd3 { get; set; }
        public string q_print_year { get; set; }
        public string q_size { get; set; }
        public string q_original_title { get; set; }
        public string q_series { get; set; }
        public string q_series_id { get; set; }
        public string q_series_partno { get; set; }
        public string q_total_no_part_series { get; set; }
        public string itemtypecd4 { get; set; }
        public string q_language { get; set; }
        public string webpublish { get; set; }
        public int id { get; set; }
    }
}
