//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STGchannelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_import_bh
    {
        public short foretagkod { get; set; }
        public string q_MessageNumber { get; set; }
        public string q_PartyIDType { get; set; }
        public string q_PartyID_Identifier { get; set; }
        public long Bestnr { get; set; }
        public string q_Seller_identifier { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public string rowupdatedby { get; set; }
        public Nullable<System.DateTime> rowupdateddt { get; set; }
        public string OrdLevAdr1 { get; set; }
        public string ohderrorcd { get; set; }
        public Nullable<System.DateTime> q_transferd { get; set; }
        public string edit { get; set; }
    }
}
