//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STGchannelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_import_bp
    {
        public short foretagkod { get; set; }
        public string q_MessageNumber { get; set; }
        public string q_PartyIDType { get; set; }
        public string q_PartyID_Identifier { get; set; }
        public long Bestnr { get; set; }
        public int BestRadNr { get; set; }
        public string Artnr { get; set; }
        public string ArtBeskr { get; set; }
        public Nullable<decimal> BestAnt { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public string rowupdatedby { get; set; }
        public Nullable<System.DateTime> rowupdateddt { get; set; }
        public Nullable<short> OrdErrorCd { get; set; }
        public string q_ExtBestRadNr { get; set; }
    }
}
