//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STGchannelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xakh
    {
        public string ArtKat { get; set; }
        public string ArtKatBeskr { get; set; }
        public short ForetagKod { get; set; }
        public Nullable<short> ICTRuleNumber { get; set; }
        public Nullable<short> IntrnCoNoOrigin { get; set; }
        public Nullable<short> No_trigger_exec { get; set; }
        public string PersSign { get; set; }
        public System.DateTime RegDat { get; set; }
        public Nullable<short> ReplicateRecord { get; set; }
        public string RowCreatedBy { get; set; }
        public System.DateTime RowCreatedDt { get; set; }
        public System.DateTime RowCreatedUTCDT { get; set; }
        public string RowUpdatedBy { get; set; }
        public string RowUpdatedCols { get; set; }
        public Nullable<System.DateTime> RowUpdatedDt { get; set; }
        public Nullable<System.DateTime> RowUpdatedUTCDT { get; set; }
        public Nullable<short> TimeZoneCode { get; set; }
        public string webbeskr { get; set; }
        public string webpublish { get; set; }
        public decimal q_default_artvikt { get; set; }
        public Nullable<short> q_ise_item_category1_id { get; set; }
    }
}
